/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/app'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppJobsRouteImport } from './routes/app/jobs'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as AppCampaignsIndexRouteImport } from './routes/app/campaigns/index'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/app/campaigns/$campaignId'
import { Route as AppCampaignsNewRouteImport } from './routes/app/campaigns/new'
import { Route as AppOperatorIndexRouteImport } from './routes/app/operator/index'
import { Route as AppOperatorTestLabRouteImport } from './routes/app/operator/test-lab'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsAutomationRouteImport } from './routes/app/settings/automation'
import { Route as AppSettingsDocumentsRouteImport } from './routes/app/settings/documents'
import { Route as AppSettingsPreferencesRouteImport } from './routes/app/settings/preferences'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsWritingStyleRouteImport } from './routes/app/settings/writing-style'
import { Route as JobPublicIdSlugRouteImport } from './routes/job/$publicId/$slug'
import { Route as JobsCountrySlugIndexRouteImport } from './routes/jobs/$countrySlug/index'
import { Route as JobsCountrySlugCitySlugRouteImport } from './routes/jobs/$countrySlug/$citySlug'
import { Route as AppCampaignsMarketsIndexRouteImport } from './routes/app/campaigns/markets/index'
import { Route as AppCampaignsMarketsCountryCodeRouteImport } from './routes/app/campaigns/markets/$countryCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorIndexRoute = AppOperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorTestLabRoute = AppOperatorTestLabRouteImport.update({
  id: '/operator/test-lab',
  path: '/operator/test-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAutomationRoute = AppSettingsAutomationRouteImport.update({
  id: '/settings/automation',
  path: '/settings/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDocumentsRoute = AppSettingsDocumentsRouteImport.update({
  id: '/settings/documents',
  path: '/settings/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWritingStyleRoute = AppSettingsWritingStyleRouteImport.update({
  id: '/settings/writing-style',
  path: '/settings/writing-style',
  getParentRoute: () => AppRoute,
} as any)
const JobPublicIdSlugRoute = JobPublicIdSlugRouteImport.update({
  id: '/job/$publicId/$slug',
  path: '/job/$publicId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCountrySlugIndexRoute = JobsCountrySlugIndexRouteImport.update({
  id: '/jobs/$countrySlug/',
  path: '/jobs/$countrySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCountrySlugCitySlugRoute = JobsCountrySlugCitySlugRouteImport.update({
  id: '/jobs/$countrySlug/$citySlug',
  path: '/jobs/$countrySlug/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsMarketsIndexRoute =
  AppCampaignsMarketsIndexRouteImport.update({
    id: '/campaigns/markets/',
    path: '/campaigns/markets/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCampaignsMarketsCountryCodeRoute =
  AppCampaignsMarketsCountryCodeRouteImport.update({
    id: '/campaigns/markets/$countryCode',
    path: '/campaigns/markets/$countryCode',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/': typeof AppIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/operator/test-lab': typeof AppOperatorTestLabRoute
  '/app/settings/automation': typeof AppSettingsAutomationRoute
  '/app/settings/documents': typeof AppSettingsDocumentsRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/writing-style': typeof AppSettingsWritingStyleRoute
  '/job/$publicId/$slug': typeof JobPublicIdSlugRoute
  '/jobs/$countrySlug/$citySlug': typeof JobsCountrySlugCitySlugRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/app/operator/': typeof AppOperatorIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/jobs/$countrySlug/': typeof JobsCountrySlugIndexRoute
  '/app/campaigns/markets/$countryCode': typeof AppCampaignsMarketsCountryCodeRoute
  '/app/campaigns/markets/': typeof AppCampaignsMarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app': typeof AppIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/operator/test-lab': typeof AppOperatorTestLabRoute
  '/app/settings/automation': typeof AppSettingsAutomationRoute
  '/app/settings/documents': typeof AppSettingsDocumentsRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/writing-style': typeof AppSettingsWritingStyleRoute
  '/job/$publicId/$slug': typeof JobPublicIdSlugRoute
  '/jobs/$countrySlug/$citySlug': typeof JobsCountrySlugCitySlugRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/app/operator': typeof AppOperatorIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/jobs/$countrySlug': typeof JobsCountrySlugIndexRoute
  '/app/campaigns/markets/$countryCode': typeof AppCampaignsMarketsCountryCodeRoute
  '/app/campaigns/markets': typeof AppCampaignsMarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/': typeof AppIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/operator/test-lab': typeof AppOperatorTestLabRoute
  '/app/settings/automation': typeof AppSettingsAutomationRoute
  '/app/settings/documents': typeof AppSettingsDocumentsRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/writing-style': typeof AppSettingsWritingStyleRoute
  '/job/$publicId/$slug': typeof JobPublicIdSlugRoute
  '/jobs/$countrySlug/$citySlug': typeof JobsCountrySlugCitySlugRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/app/operator/': typeof AppOperatorIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/jobs/$countrySlug/': typeof JobsCountrySlugIndexRoute
  '/app/campaigns/markets/$countryCode': typeof AppCampaignsMarketsCountryCodeRoute
  '/app/campaigns/markets/': typeof AppCampaignsMarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/corrections'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/app/jobs'
    | '/app/messages'
    | '/app/'
    | '/jobs/'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/operator/test-lab'
    | '/app/settings/automation'
    | '/app/settings/documents'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/writing-style'
    | '/job/$publicId/$slug'
    | '/jobs/$countrySlug/$citySlug'
    | '/app/campaigns/'
    | '/app/operator/'
    | '/app/settings/'
    | '/jobs/$countrySlug/'
    | '/app/campaigns/markets/$countryCode'
    | '/app/campaigns/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/corrections'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/app/jobs'
    | '/app/messages'
    | '/app'
    | '/jobs'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/operator/test-lab'
    | '/app/settings/automation'
    | '/app/settings/documents'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/writing-style'
    | '/job/$publicId/$slug'
    | '/jobs/$countrySlug/$citySlug'
    | '/app/campaigns'
    | '/app/operator'
    | '/app/settings'
    | '/jobs/$countrySlug'
    | '/app/campaigns/markets/$countryCode'
    | '/app/campaigns/markets'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/corrections'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/app/jobs'
    | '/app/messages'
    | '/app/'
    | '/jobs/'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/operator/test-lab'
    | '/app/settings/automation'
    | '/app/settings/documents'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/app/settings/writing-style'
    | '/job/$publicId/$slug'
    | '/jobs/$countrySlug/$citySlug'
    | '/app/campaigns/'
    | '/app/operator/'
    | '/app/settings/'
    | '/jobs/$countrySlug/'
    | '/app/campaigns/markets/$countryCode'
    | '/app/campaigns/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  CorrectionsRoute: typeof CorrectionsRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobPublicIdSlugRoute: typeof JobPublicIdSlugRoute
  JobsCountrySlugCitySlugRoute: typeof JobsCountrySlugCitySlugRoute
  JobsCountrySlugIndexRoute: typeof JobsCountrySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/$campaignId': {
      id: '/app/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/app/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/new': {
      id: '/app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/': {
      id: '/app/operator/'
      path: '/operator'
      fullPath: '/app/operator/'
      preLoaderRoute: typeof AppOperatorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/test-lab': {
      id: '/app/operator/test-lab'
      path: '/operator/test-lab'
      fullPath: '/app/operator/test-lab'
      preLoaderRoute: typeof AppOperatorTestLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/automation': {
      id: '/app/settings/automation'
      path: '/settings/automation'
      fullPath: '/app/settings/automation'
      preLoaderRoute: typeof AppSettingsAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/documents': {
      id: '/app/settings/documents'
      path: '/settings/documents'
      fullPath: '/app/settings/documents'
      preLoaderRoute: typeof AppSettingsDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/preferences': {
      id: '/app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/app/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/writing-style': {
      id: '/app/settings/writing-style'
      path: '/settings/writing-style'
      fullPath: '/app/settings/writing-style'
      preLoaderRoute: typeof AppSettingsWritingStyleRouteImport
      parentRoute: typeof AppRoute
    }
    '/job/$publicId/$slug': {
      id: '/job/$publicId/$slug'
      path: '/job/$publicId/$slug'
      fullPath: '/job/$publicId/$slug'
      preLoaderRoute: typeof JobPublicIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$countrySlug/': {
      id: '/jobs/$countrySlug/'
      path: '/jobs/$countrySlug'
      fullPath: '/jobs/$countrySlug/'
      preLoaderRoute: typeof JobsCountrySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$countrySlug/$citySlug': {
      id: '/jobs/$countrySlug/$citySlug'
      path: '/jobs/$countrySlug/$citySlug'
      fullPath: '/jobs/$countrySlug/$citySlug'
      preLoaderRoute: typeof JobsCountrySlugCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/campaigns/markets/': {
      id: '/app/campaigns/markets/'
      path: '/campaigns/markets'
      fullPath: '/app/campaigns/markets/'
      preLoaderRoute: typeof AppCampaignsMarketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/markets/$countryCode': {
      id: '/app/campaigns/markets/$countryCode'
      path: '/campaigns/markets/$countryCode'
      fullPath: '/app/campaigns/markets/$countryCode'
      preLoaderRoute: typeof AppCampaignsMarketsCountryCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppJobsRoute: typeof AppJobsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppOperatorTestLabRoute: typeof AppOperatorTestLabRoute
  AppSettingsAutomationRoute: typeof AppSettingsAutomationRoute
  AppSettingsDocumentsRoute: typeof AppSettingsDocumentsRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsWritingStyleRoute: typeof AppSettingsWritingStyleRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppOperatorIndexRoute: typeof AppOperatorIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppCampaignsMarketsCountryCodeRoute: typeof AppCampaignsMarketsCountryCodeRoute
  AppCampaignsMarketsIndexRoute: typeof AppCampaignsMarketsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJobsRoute: AppJobsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppOperatorTestLabRoute: AppOperatorTestLabRoute,
  AppSettingsAutomationRoute: AppSettingsAutomationRoute,
  AppSettingsDocumentsRoute: AppSettingsDocumentsRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsWritingStyleRoute: AppSettingsWritingStyleRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppOperatorIndexRoute: AppOperatorIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppCampaignsMarketsCountryCodeRoute: AppCampaignsMarketsCountryCodeRoute,
  AppCampaignsMarketsIndexRoute: AppCampaignsMarketsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  CorrectionsRoute: CorrectionsRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobPublicIdSlugRoute: JobPublicIdSlugRoute,
  JobsCountrySlugCitySlugRoute: JobsCountrySlugCitySlugRoute,
  JobsCountrySlugIndexRoute: JobsCountrySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
