export interface AppEnv extends Env {
  FX_RATES_JSON?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  GOOGLE_INDEXING_SERVICE_ACCOUNT_JSON?: string;
  GOOGLE_PUBSUB_AUDIENCE?: string;
  GOOGLE_PUBSUB_SERVICE_ACCOUNT?: string;
  GOOGLE_PUBSUB_TOPIC?: string;
  JINA_API_KEY?: string;
  MAPBOX_ACCESS_TOKEN?: string;
  PUBLIC_JOB_CURSOR_SECRET?: string;
  SERIOUSTEACHERS_EMAIL?: string;
  SERIOUSTEACHERS_PASSWORD?: string;
  SWEEP_OUTPUTS: R2Bucket;
}
